version: "3.8"

services:

  gitlab:
    image: gitlab/gitlab-ee:18.0.1-ee.0
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "80:80"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "89:80"
    volumes:
      - /var/www/laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-php
    networks:
      - laravel

  laravel-php:
    image: flowadmin-laravel-php
    container_name: laravel-php
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /var/www/laravel:/var/www
    networks:
      - laravel

  fail2ban-ssh:
    image: fail2ban-ssh
    container_name: f2btest
    restart: always
    ports:
      - "2222:22"
    volumes:
      - /etc/fail2ban:/etc/fail2ban
      - /var/log:/var/log

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml

networks:
  laravel:
    driver: bridge
