version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loomi_db
      MYSQL_USER: loomi
      MYSQL_PASSWORD: loomi_pass
    volumes:
      - /srv/loomi/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - loomi-net

  php:
    image: flowadmin-php
    container_name: php
    restart: always
    volumes:
      - /var/www/loomi:/var/www
    ports:
      - "8000:8000"
    networks:
      - loomi-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /var/www/loomi:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "89:80"
    depends_on:
      - php
    networks:
      - loomi-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - loomi-net

  fail2ban:
    image: fail2ban-ssh
    container_name: f2btest
    restart: always
    ports:
      - "2222:22"
    volumes:
      - /etc/fail2ban:/etc/fail2ban
      - /var/log:/var/log

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml

  portainer_agent:
    image: portainer/agent:2.27.3
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  loomi-net:
    driver: bridge