global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node_exporters
    static_configs:
      - targets:
          - 10.2.5.98:9100  # DATAFLOW
          - 10.2.5.99:9100  # LOOMI
          - 10.2.5.100:9100 # GROOP

  - job_name: gitlab
    metrics_path: "/-/metrics"
    static_configs:
      - targets: ['10.2.5.100:80']

  - job_name: promtail
    static_configs:
      - targets:
          - 10.2.5.98:9080
          - 10.2.5.99:9080
          - 10.2.5.100:9080

  - job_name: cadvisor
    static_configs:
      - targets:
          - 10.2.5.98:8080
          - 10.2.5.99:8080
          - 10.2.5.100:8080