image: node:20

stages:
  - build_deploy

build_and_deploy:
  stage: build_deploy
  tags:
    - front
  variables:
    VITE_API_BASE_URL: $VITE_API_BASE_URL
  before_script:
    - echo "🌍 Génération du fichier .env pour Vite..."
    - echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" > .env
    - echo "🔧 Installation des dépendances..."
    - npm ci
  script:
    - echo "🏗️ Build du frontend avec Vite..."
    - npm run build

    - echo "🧹 Nettoyage du dossier de déploiement..."
    - sudo mkdir -p /home/flowadmin/front/build
    - sudo rm -rf /home/flowadmin/front/build/* || true

    - echo "📁 Copie des fichiers buildés..."
    - sudo cp -r dist/* /home/flowadmin/front/build/

    - echo "♻️ Redémarrage de Nginx..."
    - sudo docker compose -f /home/flowadmin/docker-compose.yml restart nginx
  only:
    - main
